// ── System Settings & Theme ──

export type ThemeMode = "dark" | "light" | "system" | "claude-dark" | "claude-light";
export type FontFamily = "ibm" | "cairo" | "noto" | "rubik" | "inter";
export type FontSize = "sm" | "md" | "lg";
export type Language = "ar" | "en";

export interface SystemSettings {
  theme: ThemeMode;
  font: FontFamily;
  fontSize: FontSize;
  lang: Language;
  loyaltyPointsRatio: number; // SAR per 1 point (default 50)
  endOfDayHour: number;       // hour (0–23) at which the business day resets (default 5 = 5AM)
  vatNumber?: string;         // ZATCA VAT registration number (15 digits, starts+ends with 3)
  sellerNameAr?: string;      // Arabic seller name for ZATCA QR (defaults to tenant name_ar)
  vatEnabled?: boolean;       // show VAT breakdown on invoices (default false until configured)
  scanTrackerEndpoint?: string; // external expense API URL for ScanTracker integration
  whatsappNotifyMins?: number;  // minutes before session end to send WhatsApp notification (default 5)
}

export const DEFAULT_SETTINGS: SystemSettings = {
  theme: "dark",
  font: "ibm",
  fontSize: "md",
  lang: "ar",
  loyaltyPointsRatio: 50,
  endOfDayHour: 5,
  vatNumber: "",
  sellerNameAr: "",
  vatEnabled: false,
};

export const FONTS: Record<FontFamily, { name: string; nameAr: string; css: string; google: string }> = {
  ibm:   { name: "IBM Plex Sans Arabic", nameAr: "IBM بلكس", css: "'IBM Plex Sans Arabic', sans-serif", google: "IBM+Plex+Sans+Arabic:wght@300;400;500;600;700" },
  cairo: { name: "Cairo", nameAr: "القاهرة", css: "'Cairo', sans-serif", google: "Cairo:wght@300;400;500;600;700;800;900" },
  noto:  { name: "Noto Sans Arabic", nameAr: "نوتو", css: "'Noto Sans Arabic', sans-serif", google: "Noto+Sans+Arabic:wght@300;400;500;600;700;800;900" },
  rubik: { name: "Rubik", nameAr: "روبيك", css: "'Rubik', sans-serif", google: "Rubik:wght@300;400;500;600;700;800;900" },
  inter: { name: "Inter", nameAr: "إنتر", css: "'Inter', sans-serif", google: "Inter:wght@300;400;500;600;700;800;900" },
};

export const FONT_SIZES: Record<FontSize, { label: string; labelAr: string; scale: number }> = {
  sm: { label: "Small", labelAr: "صغير", scale: 0.9 },
  md: { label: "Medium", labelAr: "متوسط", scale: 1 },
  lg: { label: "Large", labelAr: "كبير", scale: 1.1 },
};

export const THEMES = {
  dark: {
    bg: "#0f0f12", bg2: "#0a0a0e", surface: "#18181d", surface2: "#222229",
    accent: "#6c8cff", accent2: "#5470e0", blue: "#5b9bf5", green: "#4ade80",
    red: "#f87171", yellow: "#fbbf24", text: "#f0f0f5", text2: "#9898a8",
    border: "rgba(255,255,255,0.06)", cardBg: "#1a1a20", cardBorder: "rgba(255,255,255,0.05)",
    inputBg: "#12121a", navBg: "rgba(15,15,18,0.92)",
  },
  light: {
    bg: "#f5f6fa", bg2: "#ffffff", surface: "#ffffff", surface2: "#f0f1f5",
    accent: "#4f6df5", accent2: "#3d58d6", blue: "#3b82f6", green: "#22c55e",
    red: "#ef4444", yellow: "#f59e0b", text: "#1a1a2e", text2: "#6b6b80",
    border: "rgba(0,0,0,0.08)", cardBg: "#ffffff", cardBorder: "rgba(0,0,0,0.06)",
    inputBg: "#f5f6fa", navBg: "rgba(255,255,255,0.92)",
  },
};

// i18n
export const T: Record<Language, Record<string, string>> = {
  ar: {
    appName: "ALSAMLAH",
    appSub: "مركز الصملة للترفيه",
    home: "الرئيسية", qr: "QR طلبات", history: "السجل", debts: "الديون", stats: "التقارير", admin: "إعدادات",
    active: "نشط", person: "شخص", today: "اليوم", week: "الأسبوع", month: "الشهر", all: "الكل",
    empty: "فارغ", press: "اضغط للفتح", overtime: "انتهى الوقت", open: "مفتوح",
    startSession: "بدء جلسة جديدة", custName: "اسم العميل", duration: "المدة",
    players: "عدد الأشخاص", start: "ابدأ الجلسة", endSession: "إنهاء الجلسة",
    bill: "الفاتورة", time: "الوقت", orders: "الطلبات", total: "المجموع",
    addOrder: "إضافة طلب", closeMenu: "إغلاق القائمة",
    cash: "كاش", card: "شبكة", transfer: "تحويل", discount: "خصم", debt: "دين",
    cashDue: "المطلوب نقداً", save: "حفظ", cancel: "إلغاء", delete: "حذف",
    freeMin: "دقائق مجانية", back: "رجوع", logout: "خروج",
    noHistory: "لا يوجد سجل", noDebts: "لا ديون", search: "بحث...",
    unpaid: "غير مسدد", paid: "مسدد", addDebt: "إضافة دين", phone: "رقم الجوال",
    amount: "المبلغ", note: "ملاحظة", pay: "تسديد", fullPay: "سداد كامل",
    payHistory: "سجل الدفعات", remaining: "المتبقي", totalDebt: "إجمالي",
    revenue: "الإيراد", sessions: "الجلسات", visitors: "الزوار", totalTime: "إجمالي الوقت",
    activeNow: "نشط الآن", revenueDetails: "تفاصيل الإيراد", timeRev: "إيراد الوقت",
    ordersRev: "إيراد الطلبات", discounts: "الخصومات", newDebts: "ديون جديدة", net: "الصافي",
    payMethods: "طرق الدفع", byZone: "حسب القسم", byCashier: "حسب الكاشير",
    topCustomers: "أكثر العملاء", debtSummary: "ملخص الديون", debtors: "عدد المدينين",
    prices: "الأسعار", menu: "القائمة", pins: "الأرقام السرية", danger: "خطر",
    pricePerHour: "سعر الساعة", minDuration: "أقل مدة (د)", menuMgmt: "إدارة القائمة",
    addItem: "إضافة صنف جديد", icon: "الأيقونة", itemName: "اسم الصنف",
    price: "السعر", category: "الفئة", newCat: "فئة جديدة", edit: "تعديل",
    currentPin: "الرقم الحالي", newPin: "رقم جديد", dangerZone: "منطقة الخطر",
    clearHistory: "مسح السجل", clearDebts: "مسح الديون",
    settings: "إعدادات النظام", font: "الخط", fontSize: "حجم الخط", theme: "المظهر",
    darkMode: "داكن", lightMode: "فاتح", systemMode: "النظام", claudeDarkMode: "كلود داكن", claudeLightMode: "كلود فاتح", language: "اللغة",
    login: "تسجيل الدخول", selectRole: "اختر طريقة الدخول", enterPin: "أدخل الرقم السري",
    wrongPin: "الرقم السري غير صحيح", cashier1: "كاشير ١", cashier2: "كاشير ٢", manager: "المدير",
    cashierAccess: "إدارة الجلسات والطلبات", managerAccess: "وصول كامل + إعدادات",
    floor1: "الطابق الأول", floor2: "الطابق الثاني", visit: "زيارة", session: "جلسة",
    perHour: "/ساعة", free: "مجاني", sar: "",
    matchSession: "جلسة مبارة", psSession: "بلايستيشن", sessionTypeLabel: "نوع الجلسة",
    fixedPrice: "السعر ثابت", coffeeRequired: "تنبيه: اشتراط طلب من الكوفي شوب",
    walkinSession: "طلب مباشر", walkinZone: "طلبات مباشرة", newWalkinOrder: "طلب جديد",
    ordersOnly: "طلبات فقط", noTimeCharge: "بدون رسوم وقت",
    manualPricing: "تسعير يدوي", manualPriceLabel: "السعر اليدوي", enterManualPrice: "أدخل السعر",
    massageSession: "جلسة مساج", openSession: "مفتوحة",
    numPeople: "عدد الأشخاص في الغرفة",
    min30: "٣٠ د", hour1: "ساعة", hour2: "ساعتين", hour3: "٣ ساعات", openTime: "مفتوح",
    addedItem: "تم إضافة الصنف", sessionStarted: "تم فتح الجلسة",
    sessionEnded: "تم إنهاء الجلسة", debtAdded: "تم إضافة الدين", paymentRecorded: "تم تسجيل الدفعة",
    done: "تم", deleted: "تم الحذف", saved: "تم الحفظ", pinChanged: "تم تغيير الرقم",
    confirmClearHistory: "مسح كل السجل؟", confirmClearDebts: "مسح كل الديون؟",
    reports: "التقارير",
    printReceipt: "طباعة الفاتورة", thermal: "🖨️ حراري", a4: "📄 A4", skip: "تخطي",
    logoSection: "شعار المركز", uploadLogo: "رفع شعار مخصص", useBuiltinLogo: "استخدم الشعار المصمم", clearLogo: "حذف الشعار",
    shift: "المناوبة", shiftStatus: "حالة المناوبة", shiftOpen: "مناوبة مفتوحة", shiftNone: "لا توجد مناوبة نشطة",
    openShift: "فتح مناوبة", closeShift: "إغلاق المناوبة", shiftOpened: "تم فتح المناوبة", shiftClosedMsg: "تم إغلاق المناوبة",
    cashFloat: "رصيد الصندوق", shiftDuration: "مدة المناوبة", shiftSummary: "ملخص المناوبة",
    shiftHistory: "سجل المناوبات", openedBy: "فتح بواسطة", closedBy: "أغلق بواسطة",
    managerOnlyClose: "إغلاق المناوبة للمدير فقط", confirmCloseShift: "إغلاق المناوبة الآن؟",
    netRevenue: "الصافي", cashRev: "نقداً", cardRev: "شبكة", transferRev: "تحويل",
    noShiftHistory: "لا يوجد سجل مناوبات",
    whatsapp: "واتساب",
    scanQr: "مسح QR", scannerUnsupported: "الماسح غير مدعوم في هذا المتصفح",
    customers: "العملاء", totalVisits: "إجمالي الزيارات", totalSpent: "إجمالي المصروف",
    points: "النقاط", bronze: "برونز", silver: "فضي", gold: "ذهبي",
    noCustomers: "لا يوجد عملاء", loyalty: "الولاء",
    specialGuests: "الزوار الخاصون", addGuest: "تسجيل زائر خاص",
    activeGuests: "الزوار الحاليون", pastGuests: "سجل الزيارات",
    noActiveGuests: "لا يوجد زوار خاصون الآن", markLeft: "غادر",
    inspectorAlert: "مراقب متواجد الآن — تنبيه",
    loyaltyPointsRatio: "معدل نقاط الولاء", perSAR: "ريال = نقطة واحدة",
    // Day management / invoice system
    invoiceNo: "رقم الفاتورة",
    hold: "تعليق ⏸", held: "معلق",
    roomOccupied: "الغرفة مشغولة", roomFree: "الغرفة شاغلة",
    completePayment: "إتمام الدفع",
    editInvoice: "تعديل الفاتورة", deleteInvoice: "حذف الفاتورة",
    endOfDay: "إغلاق اليوم",
    openingBalance: "رصيد الافتتاح", expectedDrawer: "المتوقع في الصندوق",
    itemSales: "مبيعات الأصناف", qty: "الكمية",
    exportCsv: "تصدير Excel", exportPdf: "تصدير PDF",
    bulkSelect: "تحديد متعدد", selectAll: "تحديد الكل",
    clearSelection: "إلغاء التحديد",
    dateRange: "نطاق", dateFrom: "من", dateTo: "إلى",
    printReport: "طباعة التقرير",
    heldSessions: "الجلسات المعلقة",
    selectToday: "تحديد اليوم", selectWeek: "تحديد الأسبوع", selectMonth: "تحديد الشهر",
    overview: "نظرة عامة", items: "الأصناف",
    endOfDayHour: "وقت نهاية اليوم",
    endOfDayHourNote: "كل شيء قبل هذا الوقت يُحسب لليوم السابق",
    bulkDelete: "حذف المحدد",
    editOrderLines: "تعديل الطلبات",
    removeItem: "حذف الصنف",
    totalOverride: "إجمالي مُعدَّل",
    heldOccupied: "معلق — مشغول", heldFree: "معلق — شاغل",
    holdTitle: "تعليق الجلسة", holdKeepOccupied: "الغرفة تبقى مشغولة",
    holdFreeRoom: "تحرير الغرفة", holdConfirm: "تأكيد التعليق",
    // VAT / ZATCA
    vatSection: "ضريبة القيمة المضافة (ZATCA)",
    vatNumber: "الرقم الضريبي", vatNumberNote: "١٥ رقماً، يبدأ وينتهي بـ 3",
    sellerNameAr: "اسم المنشأة (عربي)", sellerNameArNote: "الاسم الرسمي كما في السجل التجاري",
    vatEnabled: "تفعيل الفاتورة الضريبية",
    vatEnabledNote: "يضيف تفاصيل الضريبة ورمز QR للزكاة على كل فاتورة",
    vatAmount: "ضريبة القيمة المضافة (١٥٪)",
    priceBeforeVat: "المبلغ قبل الضريبة",
    priceTotalInclVat: "الإجمالي شامل الضريبة",
    zatcaCompliant: "فاتورة ضريبية متوافقة مع الزكاة والضريبة",
    // Tournaments
    tournaments: "البطولات", addTournament: "بطولة جديدة", tournamentName: "اسم البطولة",
    tournamentType: "النوع", tournamentFormat: "النظام", singleElim: "خروج مباشر", roundRobin: "دوري",
    addParticipant: "إضافة مشارك", entryFee: "رسوم التسجيل", prizePool: "الجائزة",
    generateBracket: "بدء البطولة وتوليد الجدول", enterScore: "إدخال النتيجة",
    winner: "الفائز", round: "الجولة", matchWord: "مباراة", bracket: "البراكيت",
    standings: "الترتيب", startTournament: "بدء البطولة", completeTournament: "إنهاء البطولة",
    cancelTournament: "إلغاء البطولة", registrationOpen: "التسجيل مفتوح",
    checkedIn: "حضر", eliminated: "خرج", disqualified: "مستبعد",
    teamName: "اسم الفريق", teamMembers: "أعضاء الفريق", isTeam: "فريق", individual: "فردي",
    maxParticipants: "أقصى عدد مشاركين", entryPaid: "دفع الرسوم", entryUnpaid: "لم يدفع",
    tLocation: "المكان/الطاولة", noTournaments: "لا توجد بطولات",
    activeTournaments: "نشطة", completedTournaments: "مكتملة", allTournaments: "الكل",
    tournamentWinner: "الفائز بالبطولة", printBracket: "طباعة النتائج",
    bye: "إعفاء", participantCount: "المشاركون", paidCount: "دفعوا", unpaidCount: "لم يدفعوا",
    confirmCancel: "تأكيد إلغاء البطولة؟", scoreP1: "نتيجة ١", scoreP2: "نتيجة ٢", setWinner: "تحديد الفائز",
    tps: "بلايستيشن", tbilliard: "بلياردو", tchess: "شطرنج", ttennis: "تنس الطاولة", tbaloot: "بلوت", tother: "أخرى",
    // ── Registers ──
    registers: "سجلات المتابعة", addEntry: "إضافة سجل", editEntry: "تعديل سجل",
    exportExcel: "تصدير Excel", deleteEntry: "حذف",
    equipmentMaint: "صيانة الأجهزة", cleaningLog: "النظافة",
    playstationMaint: "البلايستيشن", pestControl: "رش المبيدات",
    regStatus: "الحالة", regDate: "التاريخ", regNotes: "ملاحظات",
    regOk: "تعمل", regPending: "معلق", regIssue: "عطل",
    noEntries: "لا توجد سجلات", confirmDeleteEntry: "حذف هذا السجل؟",
    regSaved: "تم الحفظ", regDeleted: "تم الحذف",
    // ── Tiered Pricing ──
    perHit: "بالضربة", hitCount: "عدد الضربات", hitPrice: "سعر الضربة",
    openDay: "يوم مفتوح", tierPrice: "سعر الفترة", addTier: "إضافة فترة",
    extras: "إضافات",
    // ── Phone + Switch + Reports ──
    phoneNumber: "رقم الجوال", switchActivity: "تبديل النشاط", switchTo: "تبديل إلى",
    switchedFromLabel: "تم التبديل من", availableItems: "العناصر المتاحة",
    dashboard: "لوحة التحكم", summary: "ملخص", detailed: "تفصيلي",
    totalRevenue: "إجمالي الإيرادات", sessionCount: "عدد الجلسات",
    visitorCount: "عدد الزوار", avgBill: "متوسط الفاتورة",
    revenueByZone: "الإيرادات بالمنطقة",
    exportReport: "تصدير التقرير",
    noData: "لا توجد بيانات", filterBy: "فلترة",
    // Split bill / split payment / correction
    splitBill: "تقسيم الفاتورة", splitOn: "تقسيم على", perPerson: "نصيب كل شخص",
    deferredInvoice: "آجل كامل", splitPayment: "تقسيم طريقة الدفع",
    cashAmount: "مبلغ الكاش", cardAmount: "مبلغ الشبكة", transferAmount: "مبلغ التحويل",
    paymentTotal: "المجموع المدخل", paymentRemaining: "يتبقى",
    correction: "تصحيح فاتورة", correctedAmount: "المبلغ الصحيح",
    refundAmt: "مبلغ الاسترداد", refundMethodLabel: "طريقة الاسترداد",
    confirmRefund: "تأكيد التصحيح", originalTotal: "المبلغ الأصلي",
    correctedTotal: "المبلغ بعد التصحيح", refundRecorded: "تم تسجيل الاسترداد",
    totalRefunds: "إجمالي المستردات", netAfterRefunds: "الصافي بعد الاسترداد",
    persons: "أشخاص", splitMark: "مقسّمة",
    // Payment methods
    mada: "مدى", credit: "ائتماني",
    madaRev: "مدى", creditRev: "ائتماني",
    // Prepaid
    prepay: "دفع مقدم", prepayConfirm: "تأكيد الدفع المقدم",
    prepaidAmountLabel: "المدفوع مقدماً", remainingToPay: "المتبقي للدفع",
    interimReceipt: "فاتورة مؤقتة", noAdditionalAmount: "لا يوجد مبلغ إضافي",
    prepaidNote: "الجلسة لا تزال نشطة",
    // Bank fees
    bankFees: "الرسوم البنكية", madaFees: "رسوم مدى", creditFees: "رسوم الائتمانية",
    totalBankFees: "إجمالي الرسوم البنكية", netAfterFees: "الصافي بعد الرسوم",
    // VAT in EOD
    vatBreakdown: "تفصيل الضريبة", preVatAmount: "قبل الضريبة (١٥٪)",
    // ── Dashboard ──
    occupancy: "نسبة الإشغال", vsYesterday: "مقارنة بالأمس", peakHour: "ساعة الذروة",
    avgDuration: "متوسط مدة الجلسة", kpi: "مؤشرات الأداء",
    revenueByMethod: "الإيراد حسب الطريقة", cashierPerformance: "أداء الكاشير",
    peakHoursChart: "ساعات الذروة", liveData: "بيانات حية", normal: "عادي",
    // ── Bookings ──
    bookings: "الحجوزات", newBooking: "حجز جديد", bookingDate: "تاريخ الحجز",
    bookingTime: "وقت الحجز", upcomingBookings: "حجوزات قادمة", booked: "محجوز",
    bookingAlert: "تنبيه حجز", cancelBooking: "إلغاء الحجز", noBookings: "لا توجد حجوزات",
    // ── Memberships ──
    memberships: "العضويات", membershipPlans: "خطط العضوية",
    monthlyPlan: "اشتراك شهري", hoursPlan: "باقة ساعات",
    totalHours: "إجمالي الساعات", usedHours: "مستخدمة", remainingHours: "المتبقية",
    subscribeMember: "تسجيل عضوية", memberBadge: "عضو",
    expired: "منتهية", depleted: "مستنفدة", activePlan: "نشطة",
    planName: "اسم الخطة", planPrice: "سعر الخطة", discountPct: "نسبة الخصم",
    durationDays: "المدة (أيام)", noMemberships: "لا توجد عضويات",
    noPlans: "لا توجد خطط", addPlan: "إضافة خطة",
    // ── Promotions ──
    promotions: "العروض", happyHour: "ساعة سعيدة", weekendDeal: "عرض نهاية الأسبوع",
    coupon: "كوبون", couponCode: "رمز الكوبون", discountPercent: "نسبة الخصم",
    validFrom: "صالح من", validTo: "صالح حتى", addPromotion: "إضافة عرض",
    activePromotions: "العروض النشطة", noPromotions: "لا توجد عروض",
    promoApplied: "تم تطبيق العرض", startTimeLabel: "من الساعة", endTimeLabel: "إلى الساعة",
    // ── Inventory ──
    inventory: "المخزون", stock: "الكمية", lowStock: "مخزون منخفض",
    lowStockAlert: "تنبيه مخزون", trackStock: "تتبع المخزون",
    outOfStock: "نفد", salesByItem: "مبيعات الأصناف", restock: "إعادة تعبئة",
    // ── Maintenance ──
    maintenance: "الصيانة", maintenanceStatus: "حالة الجهاز",
    inMaintenance: "تحت الصيانة", disabled: "معطل",
    maintenanceLog: "سجل الصيانة", maintenanceCost: "تكلفة الصيانة",
    addMaintenanceLog: "إضافة سجل صيانة", repairType: "نوع الصيانة",
    activate: "تفعيل", deactivate: "إيقاف", repair: "إصلاح",
    routine: "دوري", inspection: "فحص", noMaintenanceLogs: "لا توجد سجلات صيانة",
    // ── Notifications ──
    sessionNotification: "إشعار الجلسة", beforeSessionEnds: "قبل انتهاء الجلسة",
    sendWhatsApp: "إرسال واتساب", countdownDisplay: "عرض العد التنازلي",
    minutesBefore: "دقائق قبل الانتهاء", notifySent: "تم الإرسال",
    // ── Expense Export ──
    exportRevenue: "تصدير الإيرادات", scantracker: "سكان تراكر",
    exportToApi: "تصدير للنظام الخارجي", apiEndpoint: "رابط API",
    exportSuccess: "تم التصدير بنجاح", apiEndpointSetting: "رابط سكان تراكر",
    // ── Customer notes ──
    customerNotes: "ملاحظات العميل", linkedDebts: "الديون المرتبطة",
    visitHistory: "سجل الزيارات",
  },
  en: {
    appName: "ALSAMLAH",
    appSub: "Al Samlah Entertainment Center",
    home: "Home", qr: "QR Orders", history: "History", debts: "Debts", stats: "Reports", admin: "Settings",
    active: "Active", person: "Person", today: "Today", week: "Week", month: "Month", all: "All",
    empty: "Empty", press: "Tap to open", overtime: "Overtime!", open: "Open",
    startSession: "Start New Session", custName: "Customer Name", duration: "Duration",
    players: "Players", start: "Start Session", endSession: "End Session",
    bill: "Bill", time: "Time", orders: "Orders", total: "Total",
    addOrder: "Add Order", closeMenu: "Close Menu",
    cash: "Cash", card: "Card", transfer: "Transfer", discount: "Discount", debt: "Debt",
    cashDue: "Cash Due", save: "Save", cancel: "Cancel", delete: "Delete",
    freeMin: "Free Minutes", back: "Back", logout: "Logout",
    noHistory: "No history", noDebts: "No debts", search: "Search...",
    unpaid: "Unpaid", paid: "Paid", addDebt: "Add Debt", phone: "Phone",
    amount: "Amount", note: "Note", pay: "Pay", fullPay: "Full Payment",
    payHistory: "Payment History", remaining: "Remaining", totalDebt: "Total",
    revenue: "Revenue", sessions: "Sessions", visitors: "Visitors", totalTime: "Total Time",
    activeNow: "Active Now", revenueDetails: "Revenue Details", timeRev: "Time Revenue",
    ordersRev: "Orders Revenue", discounts: "Discounts", newDebts: "New Debts", net: "Net",
    payMethods: "Payment Methods", byZone: "By Zone", byCashier: "By Cashier",
    topCustomers: "Top Customers", debtSummary: "Debt Summary", debtors: "Debtors",
    prices: "Prices", menu: "Menu", pins: "PINs", danger: "Danger",
    pricePerHour: "Price/Hour", minDuration: "Min Duration (m)", menuMgmt: "Menu Management",
    addItem: "Add New Item", icon: "Icon", itemName: "Item Name",
    price: "Price", category: "Category", newCat: "New Category", edit: "Edit",
    currentPin: "Current PIN", newPin: "New PIN", dangerZone: "Danger Zone",
    clearHistory: "Clear History", clearDebts: "Clear Debts",
    settings: "System Settings", font: "Font", fontSize: "Font Size", theme: "Theme",
    darkMode: "Dark", lightMode: "Light", systemMode: "System", claudeDarkMode: "Claude Dark", claudeLightMode: "Claude Light", language: "Language",
    login: "Login", selectRole: "Select Login Method", enterPin: "Enter PIN",
    wrongPin: "Wrong PIN", cashier1: "Cashier 1", cashier2: "Cashier 2", manager: "Manager",
    cashierAccess: "Manage sessions & orders", managerAccess: "Full access + settings",
    floor1: "First Floor", floor2: "Second Floor", visit: "visit", session: "session",
    perHour: "SAR/hr", free: "Free", sar: "SAR",
    matchSession: "Match Session", psSession: "PlayStation", sessionTypeLabel: "Session Type",
    fixedPrice: "Fixed Price", coffeeRequired: "Note: Coffee shop order required",
    walkinSession: "Walk-in Order", walkinZone: "Direct Orders", newWalkinOrder: "New Order",
    ordersOnly: "Orders Only", noTimeCharge: "No time charge",
    manualPricing: "Manual Pricing", manualPriceLabel: "Manual Price", enterManualPrice: "Enter Price",
    massageSession: "Massage Session", openSession: "Open",
    numPeople: "People in room",
    min30: "30m", hour1: "1 Hour", hour2: "2 Hours", hour3: "3 Hours", openTime: "Open",
    addedItem: "Item added", sessionStarted: "Session started",
    sessionEnded: "Session ended", debtAdded: "Debt added", paymentRecorded: "Payment recorded",
    done: "Done", deleted: "Deleted", saved: "Saved", pinChanged: "PIN changed",
    confirmClearHistory: "Clear all history?", confirmClearDebts: "Clear all debts?",
    reports: "Reports",
    printReceipt: "Print Receipt", thermal: "🖨️ Thermal", a4: "📄 A4", skip: "Skip",
    logoSection: "Center Logo", uploadLogo: "Upload Custom Logo", useBuiltinLogo: "Use Built-in Logo", clearLogo: "Clear Logo",
    shift: "Shift", shiftStatus: "Shift Status", shiftOpen: "Shift Open", shiftNone: "No Active Shift",
    openShift: "Open Shift", closeShift: "Close Shift", shiftOpened: "Shift opened", shiftClosedMsg: "Shift closed",
    cashFloat: "Cash Float", shiftDuration: "Shift Duration", shiftSummary: "Shift Summary",
    shiftHistory: "Shift History", openedBy: "Opened by", closedBy: "Closed by",
    managerOnlyClose: "Closing shifts is manager only", confirmCloseShift: "Close shift now?",
    netRevenue: "Net", cashRev: "Cash", cardRev: "Card", transferRev: "Transfer",
    noShiftHistory: "No shift history",
    whatsapp: "WhatsApp",
    scanQr: "Scan QR", scannerUnsupported: "Scanner not supported in this browser",
    customers: "Customers", totalVisits: "Total Visits", totalSpent: "Total Spent",
    points: "Points", bronze: "Bronze", silver: "Silver", gold: "Gold",
    noCustomers: "No customers yet", loyalty: "Loyalty",
    specialGuests: "Special Guests", addGuest: "Register Special Guest",
    activeGuests: "Active Guests", pastGuests: "Visit History",
    noActiveGuests: "No special guests currently", markLeft: "Mark as Left",
    inspectorAlert: "Inspector on premises — Alert",
    loyaltyPointsRatio: "Loyalty Points Rate", perSAR: "SAR = 1 point",
    // Day management / invoice system
    invoiceNo: "Invoice #",
    hold: "Hold ⏸", held: "Held",
    roomOccupied: "Room stays occupied", roomFree: "Free the room",
    completePayment: "Complete Payment",
    editInvoice: "Edit Invoice", deleteInvoice: "Delete Invoice",
    endOfDay: "End of Day",
    openingBalance: "Opening Balance", expectedDrawer: "Expected in Drawer",
    itemSales: "Item Sales", qty: "Qty",
    exportCsv: "Export Excel", exportPdf: "Export PDF",
    bulkSelect: "Multi-select", selectAll: "Select All",
    clearSelection: "Clear Selection",
    dateRange: "Range", dateFrom: "From", dateTo: "To",
    printReport: "Print Report",
    heldSessions: "Held Sessions",
    selectToday: "Select Today", selectWeek: "Select Week", selectMonth: "Select Month",
    overview: "Overview", items: "Items",
    endOfDayHour: "End-of-Day Hour",
    endOfDayHourNote: "Hours before this time count as the previous day",
    bulkDelete: "Delete Selected",
    editOrderLines: "Edit Orders",
    removeItem: "Remove Item",
    totalOverride: "Override Total",
    heldOccupied: "Held — Occupied", heldFree: "Held — Free",
    holdTitle: "Hold Session", holdKeepOccupied: "Keep room occupied",
    holdFreeRoom: "Free the room", holdConfirm: "Confirm Hold",
    // VAT / ZATCA
    vatSection: "VAT — ZATCA Compliance",
    vatNumber: "VAT Registration Number", vatNumberNote: "15 digits, starts & ends with 3",
    sellerNameAr: "Seller Name (Arabic)", sellerNameArNote: "Official name as per commercial register",
    vatEnabled: "Enable Tax Invoice",
    vatEnabledNote: "Adds VAT breakdown and ZATCA QR code to every invoice",
    vatAmount: "VAT Amount (15%)",
    priceBeforeVat: "Amount before VAT",
    priceTotalInclVat: "Total incl. VAT",
    zatcaCompliant: "ZATCA-compliant tax invoice",
    // Tournaments
    tournaments: "Tournaments", addTournament: "New Tournament", tournamentName: "Tournament Name",
    tournamentType: "Type", tournamentFormat: "Format", singleElim: "Single Elimination", roundRobin: "Round Robin",
    addParticipant: "Add Participant", entryFee: "Entry Fee", prizePool: "Prize",
    generateBracket: "Start & Generate Bracket", enterScore: "Enter Score",
    winner: "Winner", round: "Round", matchWord: "Match", bracket: "Bracket",
    standings: "Standings", startTournament: "Start Tournament", completeTournament: "Complete Tournament",
    cancelTournament: "Cancel Tournament", registrationOpen: "Registration Open",
    checkedIn: "Checked In", eliminated: "Eliminated", disqualified: "Disqualified",
    teamName: "Team Name", teamMembers: "Team Members", isTeam: "Team", individual: "Individual",
    maxParticipants: "Max Participants", entryPaid: "Paid", entryUnpaid: "Unpaid",
    tLocation: "Location/Table", noTournaments: "No tournaments yet",
    activeTournaments: "Active", completedTournaments: "Completed", allTournaments: "All",
    tournamentWinner: "Tournament Winner", printBracket: "Print Results",
    bye: "BYE", participantCount: "Participants", paidCount: "Paid", unpaidCount: "Unpaid",
    confirmCancel: "Confirm cancel tournament?", scoreP1: "Score 1", scoreP2: "Score 2", setWinner: "Set Winner",
    tps: "PlayStation", tbilliard: "Billiards", tchess: "Chess", ttennis: "Table Tennis", tbaloot: "Baloot", tother: "Other",
    // Registers
    registers: "Inspection Logs", addEntry: "Add Entry", editEntry: "Edit Entry",
    exportExcel: "Export Excel", deleteEntry: "Delete",
    equipmentMaint: "Equipment Maintenance", cleaningLog: "Cleaning",
    playstationMaint: "PlayStation", pestControl: "Pest Control",
    regStatus: "Status", regDate: "Date", regNotes: "Notes",
    regOk: "OK", regPending: "Pending", regIssue: "Issue",
    noEntries: "No entries yet", confirmDeleteEntry: "Delete this entry?",
    regSaved: "Saved", regDeleted: "Deleted",
    // Tiered Pricing
    perHit: "Per Hit", hitCount: "Hit Count", hitPrice: "Hit Price",
    openDay: "Open Day", tierPrice: "Tier Price", addTier: "Add Tier",
    extras: "Extras",
    // Phone + Switch + Reports
    phoneNumber: "Phone", switchActivity: "Switch Activity", switchTo: "Switch to",
    switchedFromLabel: "Switched from", availableItems: "Available Items",
    dashboard: "Dashboard", summary: "Summary", detailed: "Detailed",
    totalRevenue: "Total Revenue", sessionCount: "Sessions",
    visitorCount: "Visitors", avgBill: "Avg Bill",
    revenueByZone: "Revenue by Zone", paymentMethods: "Payment Methods",
    exportReport: "Export Report",
    noData: "No data", filterBy: "Filter",
    // Split bill / split payment / correction
    splitBill: "Split Bill", splitOn: "Split between", perPerson: "Per person",
    deferredInvoice: "Full Defer", splitPayment: "Split Payment",
    cashAmount: "Cash amount", cardAmount: "Card amount", transferAmount: "Transfer amount",
    paymentTotal: "Total entered", paymentRemaining: "Remaining",
    correction: "Correct Invoice", correctedAmount: "Correct amount",
    refundAmt: "Refund amount", refundMethodLabel: "Refund method",
    confirmRefund: "Confirm Correction", originalTotal: "Original total",
    correctedTotal: "Corrected total", refundRecorded: "Refund recorded",
    totalRefunds: "Total Refunds", netAfterRefunds: "Net after refunds",
    persons: "persons", splitMark: "Split",
    // Payment methods
    mada: "Mada", credit: "Credit",
    madaRev: "Mada", creditRev: "Credit Card",
    // Prepaid
    prepay: "Advance Pay", prepayConfirm: "Confirm Advance Payment",
    prepaidAmountLabel: "Prepaid Amount", remainingToPay: "Remaining to Pay",
    interimReceipt: "Interim Receipt", noAdditionalAmount: "No additional amount",
    prepaidNote: "Session still active",
    // Bank fees
    bankFees: "Bank Fees", madaFees: "Mada Fees", creditFees: "Credit Fees",
    totalBankFees: "Total Bank Fees", netAfterFees: "Net After Fees",
    // VAT in EOD
    vatBreakdown: "VAT Breakdown", preVatAmount: "Before VAT (15%)",
    // ── Dashboard ──
    occupancy: "Occupancy", vsYesterday: "vs Yesterday", peakHour: "Peak Hour",
    avgDuration: "Avg Duration", kpi: "KPIs",
    revenueByMethod: "Revenue by Method", cashierPerformance: "Cashier Performance",
    peakHoursChart: "Peak Hours", liveData: "Live Data", normal: "Normal",
    // ── Bookings ──
    bookings: "Bookings", newBooking: "New Booking", bookingDate: "Booking Date",
    bookingTime: "Booking Time", upcomingBookings: "Upcoming", booked: "Booked",
    bookingAlert: "Booking Alert", cancelBooking: "Cancel Booking", noBookings: "No bookings",
    // ── Memberships ──
    memberships: "Memberships", membershipPlans: "Plans",
    monthlyPlan: "Monthly", hoursPlan: "Hours Package",
    totalHours: "Total Hours", usedHours: "Used", remainingHours: "Remaining",
    subscribeMember: "Subscribe", memberBadge: "Member",
    expired: "Expired", depleted: "Depleted", activePlan: "Active",
    planName: "Plan Name", planPrice: "Plan Price", discountPct: "Discount %",
    durationDays: "Duration (days)", noMemberships: "No memberships",
    noPlans: "No plans", addPlan: "Add Plan",
    // ── Promotions ──
    promotions: "Promotions", happyHour: "Happy Hour", weekendDeal: "Weekend Deal",
    coupon: "Coupon", couponCode: "Coupon Code", discountPercent: "Discount %",
    validFrom: "Valid From", validTo: "Valid Until", addPromotion: "Add Promotion",
    activePromotions: "Active Promotions", noPromotions: "No promotions",
    promoApplied: "Promotion applied", startTimeLabel: "From", endTimeLabel: "To",
    // ── Inventory ──
    inventory: "Inventory", stock: "Stock", lowStock: "Low Stock",
    lowStockAlert: "Stock Alert", trackStock: "Track Stock",
    outOfStock: "Out of Stock", salesByItem: "Sales by Item", restock: "Restock",
    // ── Maintenance ──
    maintenance: "Maintenance", maintenanceStatus: "Device Status",
    inMaintenance: "In Maintenance", disabled: "Disabled",
    maintenanceLog: "Maintenance Log", maintenanceCost: "Maintenance Cost",
    addMaintenanceLog: "Add Log", repairType: "Repair Type",
    activate: "Activate", deactivate: "Deactivate", repair: "Repair",
    routine: "Routine", inspection: "Inspection", noMaintenanceLogs: "No maintenance logs",
    // ── Notifications ──
    sessionNotification: "Session Alert", beforeSessionEnds: "Before Session Ends",
    sendWhatsApp: "Send WhatsApp", countdownDisplay: "Countdown Display",
    minutesBefore: "Minutes Before End", notifySent: "Sent",
    // ── Expense Export ──
    exportRevenue: "Export Revenue", scantracker: "ScanTracker",
    exportToApi: "Export to External", apiEndpoint: "API Endpoint",
    exportSuccess: "Exported successfully", apiEndpointSetting: "ScanTracker URL",
    // ── Customer notes ──
    customerNotes: "Customer Notes", linkedDebts: "Linked Debts",
    visitHistory: "Visit History",
  },
};
