// ── System Settings & Theme ──

export type ThemeMode = "dark" | "light" | "system" | "claude-dark" | "claude-light";
export type FontFamily = "ibm" | "cairo" | "noto" | "rubik" | "inter";
export type FontSize = "sm" | "md" | "lg";
export type Language = "ar" | "en";

export interface SystemSettings {
  theme: ThemeMode;
  font: FontFamily;
  fontSize: FontSize;
  lang: Language;
  loyaltyPointsRatio: number; // SAR per 1 point (default 50)
  endOfDayHour: number;       // hour (0–23) at which the business day resets (default 5 = 5AM)
}

export const DEFAULT_SETTINGS: SystemSettings = {
  theme: "dark",
  font: "ibm",
  fontSize: "md",
  lang: "ar",
  loyaltyPointsRatio: 50,
  endOfDayHour: 5,
};

export const FONTS: Record<FontFamily, { name: string; nameAr: string; css: string; google: string }> = {
  ibm:   { name: "IBM Plex Sans Arabic", nameAr: "IBM بلكس", css: "'IBM Plex Sans Arabic', sans-serif", google: "IBM+Plex+Sans+Arabic:wght@300;400;500;600;700" },
  cairo: { name: "Cairo", nameAr: "القاهرة", css: "'Cairo', sans-serif", google: "Cairo:wght@300;400;500;600;700;800;900" },
  noto:  { name: "Noto Sans Arabic", nameAr: "نوتو", css: "'Noto Sans Arabic', sans-serif", google: "Noto+Sans+Arabic:wght@300;400;500;600;700;800;900" },
  rubik: { name: "Rubik", nameAr: "روبيك", css: "'Rubik', sans-serif", google: "Rubik:wght@300;400;500;600;700;800;900" },
  inter: { name: "Inter", nameAr: "إنتر", css: "'Inter', sans-serif", google: "Inter:wght@300;400;500;600;700;800;900" },
};

export const FONT_SIZES: Record<FontSize, { label: string; labelAr: string; scale: number }> = {
  sm: { label: "Small", labelAr: "صغير", scale: 0.9 },
  md: { label: "Medium", labelAr: "متوسط", scale: 1 },
  lg: { label: "Large", labelAr: "كبير", scale: 1.1 },
};

export const THEMES = {
  dark: {
    bg: "#0f0f12", bg2: "#0a0a0e", surface: "#18181d", surface2: "#222229",
    accent: "#6c8cff", accent2: "#5470e0", blue: "#5b9bf5", green: "#4ade80",
    red: "#f87171", yellow: "#fbbf24", text: "#f0f0f5", text2: "#9898a8",
    border: "rgba(255,255,255,0.06)", cardBg: "#1a1a20", cardBorder: "rgba(255,255,255,0.05)",
    inputBg: "#12121a", navBg: "rgba(15,15,18,0.92)",
  },
  light: {
    bg: "#f5f6fa", bg2: "#ffffff", surface: "#ffffff", surface2: "#f0f1f5",
    accent: "#4f6df5", accent2: "#3d58d6", blue: "#3b82f6", green: "#22c55e",
    red: "#ef4444", yellow: "#f59e0b", text: "#1a1a2e", text2: "#6b6b80",
    border: "rgba(0,0,0,0.08)", cardBg: "#ffffff", cardBorder: "rgba(0,0,0,0.06)",
    inputBg: "#f5f6fa", navBg: "rgba(255,255,255,0.92)",
  },
};

// i18n
export const T: Record<Language, Record<string, string>> = {
  ar: {
    appName: "ALSAMLAH",
    appSub: "مركز الصملة للترفيه",
    home: "الرئيسية", qr: "QR طلبات", history: "السجل", debts: "الديون", stats: "التقارير", admin: "إعدادات",
    active: "نشط", person: "شخص", today: "اليوم", week: "الأسبوع", month: "الشهر", all: "الكل",
    empty: "فارغ", press: "اضغط للفتح", overtime: "انتهى الوقت", open: "مفتوح",
    startSession: "بدء جلسة جديدة", custName: "اسم العميل", duration: "المدة",
    players: "عدد الأشخاص", start: "ابدأ الجلسة", endSession: "إنهاء الجلسة",
    bill: "الفاتورة", time: "الوقت", orders: "الطلبات", total: "المجموع",
    addOrder: "إضافة طلب", closeMenu: "إغلاق القائمة",
    cash: "كاش", card: "شبكة", transfer: "تحويل", discount: "خصم", debt: "دين",
    cashDue: "المطلوب نقداً", save: "حفظ", cancel: "إلغاء", delete: "حذف",
    freeMin: "دقائق مجانية", back: "رجوع", logout: "خروج",
    noHistory: "لا يوجد سجل", noDebts: "لا ديون", search: "بحث...",
    unpaid: "غير مسدد", paid: "مسدد", addDebt: "إضافة دين", phone: "رقم الجوال",
    amount: "المبلغ", note: "ملاحظة", pay: "تسديد", fullPay: "سداد كامل",
    payHistory: "سجل الدفعات", remaining: "المتبقي", totalDebt: "إجمالي",
    revenue: "الإيراد", sessions: "الجلسات", visitors: "الزوار", totalTime: "إجمالي الوقت",
    activeNow: "نشط الآن", revenueDetails: "تفاصيل الإيراد", timeRev: "إيراد الوقت",
    ordersRev: "إيراد الطلبات", discounts: "الخصومات", newDebts: "ديون جديدة", net: "الصافي",
    payMethods: "طرق الدفع", byZone: "حسب القسم", byCashier: "حسب الكاشير",
    topCustomers: "أكثر العملاء", debtSummary: "ملخص الديون", debtors: "عدد المدينين",
    prices: "الأسعار", menu: "القائمة", pins: "الأرقام السرية", danger: "خطر",
    pricePerHour: "سعر الساعة", minDuration: "أقل مدة (د)", menuMgmt: "إدارة القائمة",
    addItem: "إضافة صنف جديد", icon: "الأيقونة", itemName: "اسم الصنف",
    price: "السعر", category: "الفئة", newCat: "فئة جديدة", edit: "تعديل",
    currentPin: "الرقم الحالي", newPin: "رقم جديد", dangerZone: "منطقة الخطر",
    clearHistory: "مسح السجل", clearDebts: "مسح الديون",
    settings: "إعدادات النظام", font: "الخط", fontSize: "حجم الخط", theme: "المظهر",
    darkMode: "داكن", lightMode: "فاتح", systemMode: "النظام", claudeDarkMode: "كلود داكن", claudeLightMode: "كلود فاتح", language: "اللغة",
    login: "تسجيل الدخول", selectRole: "اختر طريقة الدخول", enterPin: "أدخل الرقم السري",
    wrongPin: "الرقم السري غير صحيح", cashier1: "كاشير ١", cashier2: "كاشير ٢", manager: "المدير",
    cashierAccess: "إدارة الجلسات والطلبات", managerAccess: "وصول كامل + إعدادات",
    floor1: "الطابق الأول", floor2: "الطابق الثاني", visit: "زيارة", session: "جلسة",
    perHour: "/ساعة", free: "مجاني", sar: "",
    matchSession: "جلسة مبارة", psSession: "بلايستيشن", sessionTypeLabel: "نوع الجلسة",
    fixedPrice: "السعر ثابت", coffeeRequired: "تنبيه: اشتراط طلب من الكوفي شوب",
    numPeople: "عدد الأشخاص في الغرفة",
    min30: "٣٠ د", hour1: "ساعة", hour2: "ساعتين", hour3: "٣ ساعات", openTime: "مفتوح",
    addedItem: "تم إضافة الصنف", sessionStarted: "تم فتح الجلسة",
    sessionEnded: "تم إنهاء الجلسة", debtAdded: "تم إضافة الدين", paymentRecorded: "تم تسجيل الدفعة",
    done: "تم", deleted: "تم الحذف", saved: "تم الحفظ", pinChanged: "تم تغيير الرقم",
    confirmClearHistory: "مسح كل السجل؟", confirmClearDebts: "مسح كل الديون؟",
    reports: "التقارير",
    printReceipt: "طباعة الفاتورة", thermal: "🖨️ حراري", a4: "📄 A4", skip: "تخطي",
    logoSection: "شعار المركز", uploadLogo: "رفع شعار مخصص", useBuiltinLogo: "استخدم الشعار المصمم", clearLogo: "حذف الشعار",
    shift: "المناوبة", shiftStatus: "حالة المناوبة", shiftOpen: "مناوبة مفتوحة", shiftNone: "لا توجد مناوبة نشطة",
    openShift: "فتح مناوبة", closeShift: "إغلاق المناوبة", shiftOpened: "تم فتح المناوبة", shiftClosedMsg: "تم إغلاق المناوبة",
    cashFloat: "رصيد الصندوق", shiftDuration: "مدة المناوبة", shiftSummary: "ملخص المناوبة",
    shiftHistory: "سجل المناوبات", openedBy: "فتح بواسطة", closedBy: "أغلق بواسطة",
    managerOnlyClose: "إغلاق المناوبة للمدير فقط", confirmCloseShift: "إغلاق المناوبة الآن؟",
    netRevenue: "الصافي", cashRev: "نقداً", cardRev: "شبكة", transferRev: "تحويل",
    noShiftHistory: "لا يوجد سجل مناوبات",
    whatsapp: "واتساب",
    scanQr: "مسح QR", scannerUnsupported: "الماسح غير مدعوم في هذا المتصفح",
    customers: "العملاء", totalVisits: "إجمالي الزيارات", totalSpent: "إجمالي المصروف",
    points: "النقاط", bronze: "برونز", silver: "فضي", gold: "ذهبي",
    noCustomers: "لا يوجد عملاء", loyalty: "الولاء",
    specialGuests: "الزوار الخاصون", addGuest: "تسجيل زائر خاص",
    activeGuests: "الزوار الحاليون", pastGuests: "سجل الزيارات",
    noActiveGuests: "لا يوجد زوار خاصون الآن", markLeft: "غادر",
    inspectorAlert: "مراقب متواجد الآن — تنبيه",
    loyaltyPointsRatio: "معدل نقاط الولاء", perSAR: "ريال = نقطة واحدة",
    // Day management / invoice system
    invoiceNo: "رقم الفاتورة",
    hold: "تعليق ⏸", held: "معلق",
    roomOccupied: "الغرفة مشغولة", roomFree: "الغرفة شاغلة",
    completePayment: "إتمام الدفع",
    editInvoice: "تعديل الفاتورة", deleteInvoice: "حذف الفاتورة",
    endOfDay: "إغلاق اليوم",
    openingBalance: "رصيد الافتتاح", expectedDrawer: "المتوقع في الصندوق",
    itemSales: "مبيعات الأصناف", qty: "الكمية",
    exportCsv: "تصدير Excel", exportPdf: "تصدير PDF",
    bulkSelect: "تحديد متعدد", selectAll: "تحديد الكل",
    clearSelection: "إلغاء التحديد",
    dateRange: "نطاق", dateFrom: "من", dateTo: "إلى",
    printReport: "طباعة التقرير",
    heldSessions: "الجلسات المعلقة",
    selectToday: "تحديد اليوم", selectWeek: "تحديد الأسبوع", selectMonth: "تحديد الشهر",
    overview: "نظرة عامة", items: "الأصناف",
    endOfDayHour: "وقت نهاية اليوم",
    endOfDayHourNote: "كل شيء قبل هذا الوقت يُحسب لليوم السابق",
    bulkDelete: "حذف المحدد",
    editOrderLines: "تعديل الطلبات",
    removeItem: "حذف الصنف",
    totalOverride: "إجمالي مُعدَّل",
    heldOccupied: "معلق — مشغول", heldFree: "معلق — شاغل",
    holdTitle: "تعليق الجلسة", holdKeepOccupied: "الغرفة تبقى مشغولة",
    holdFreeRoom: "تحرير الغرفة", holdConfirm: "تأكيد التعليق",
  },
  en: {
    appName: "ALSAMLAH",
    appSub: "Al Samlah Entertainment Center",
    home: "Home", qr: "QR Orders", history: "History", debts: "Debts", stats: "Reports", admin: "Settings",
    active: "Active", person: "Person", today: "Today", week: "Week", month: "Month", all: "All",
    empty: "Empty", press: "Tap to open", overtime: "Overtime!", open: "Open",
    startSession: "Start New Session", custName: "Customer Name", duration: "Duration",
    players: "Players", start: "Start Session", endSession: "End Session",
    bill: "Bill", time: "Time", orders: "Orders", total: "Total",
    addOrder: "Add Order", closeMenu: "Close Menu",
    cash: "Cash", card: "Card", transfer: "Transfer", discount: "Discount", debt: "Debt",
    cashDue: "Cash Due", save: "Save", cancel: "Cancel", delete: "Delete",
    freeMin: "Free Minutes", back: "Back", logout: "Logout",
    noHistory: "No history", noDebts: "No debts", search: "Search...",
    unpaid: "Unpaid", paid: "Paid", addDebt: "Add Debt", phone: "Phone",
    amount: "Amount", note: "Note", pay: "Pay", fullPay: "Full Payment",
    payHistory: "Payment History", remaining: "Remaining", totalDebt: "Total",
    revenue: "Revenue", sessions: "Sessions", visitors: "Visitors", totalTime: "Total Time",
    activeNow: "Active Now", revenueDetails: "Revenue Details", timeRev: "Time Revenue",
    ordersRev: "Orders Revenue", discounts: "Discounts", newDebts: "New Debts", net: "Net",
    payMethods: "Payment Methods", byZone: "By Zone", byCashier: "By Cashier",
    topCustomers: "Top Customers", debtSummary: "Debt Summary", debtors: "Debtors",
    prices: "Prices", menu: "Menu", pins: "PINs", danger: "Danger",
    pricePerHour: "Price/Hour", minDuration: "Min Duration (m)", menuMgmt: "Menu Management",
    addItem: "Add New Item", icon: "Icon", itemName: "Item Name",
    price: "Price", category: "Category", newCat: "New Category", edit: "Edit",
    currentPin: "Current PIN", newPin: "New PIN", dangerZone: "Danger Zone",
    clearHistory: "Clear History", clearDebts: "Clear Debts",
    settings: "System Settings", font: "Font", fontSize: "Font Size", theme: "Theme",
    darkMode: "Dark", lightMode: "Light", systemMode: "System", claudeDarkMode: "Claude Dark", claudeLightMode: "Claude Light", language: "Language",
    login: "Login", selectRole: "Select Login Method", enterPin: "Enter PIN",
    wrongPin: "Wrong PIN", cashier1: "Cashier 1", cashier2: "Cashier 2", manager: "Manager",
    cashierAccess: "Manage sessions & orders", managerAccess: "Full access + settings",
    floor1: "First Floor", floor2: "Second Floor", visit: "visit", session: "session",
    perHour: "SAR/hr", free: "Free", sar: "SAR",
    matchSession: "Match Session", psSession: "PlayStation", sessionTypeLabel: "Session Type",
    fixedPrice: "Fixed Price", coffeeRequired: "Note: Coffee shop order required",
    numPeople: "People in room",
    min30: "30m", hour1: "1 Hour", hour2: "2 Hours", hour3: "3 Hours", openTime: "Open",
    addedItem: "Item added", sessionStarted: "Session started",
    sessionEnded: "Session ended", debtAdded: "Debt added", paymentRecorded: "Payment recorded",
    done: "Done", deleted: "Deleted", saved: "Saved", pinChanged: "PIN changed",
    confirmClearHistory: "Clear all history?", confirmClearDebts: "Clear all debts?",
    reports: "Reports",
    printReceipt: "Print Receipt", thermal: "🖨️ Thermal", a4: "📄 A4", skip: "Skip",
    logoSection: "Center Logo", uploadLogo: "Upload Custom Logo", useBuiltinLogo: "Use Built-in Logo", clearLogo: "Clear Logo",
    shift: "Shift", shiftStatus: "Shift Status", shiftOpen: "Shift Open", shiftNone: "No Active Shift",
    openShift: "Open Shift", closeShift: "Close Shift", shiftOpened: "Shift opened", shiftClosedMsg: "Shift closed",
    cashFloat: "Cash Float", shiftDuration: "Shift Duration", shiftSummary: "Shift Summary",
    shiftHistory: "Shift History", openedBy: "Opened by", closedBy: "Closed by",
    managerOnlyClose: "Closing shifts is manager only", confirmCloseShift: "Close shift now?",
    netRevenue: "Net", cashRev: "Cash", cardRev: "Card", transferRev: "Transfer",
    noShiftHistory: "No shift history",
    whatsapp: "WhatsApp",
    scanQr: "Scan QR", scannerUnsupported: "Scanner not supported in this browser",
    customers: "Customers", totalVisits: "Total Visits", totalSpent: "Total Spent",
    points: "Points", bronze: "Bronze", silver: "Silver", gold: "Gold",
    noCustomers: "No customers yet", loyalty: "Loyalty",
    specialGuests: "Special Guests", addGuest: "Register Special Guest",
    activeGuests: "Active Guests", pastGuests: "Visit History",
    noActiveGuests: "No special guests currently", markLeft: "Mark as Left",
    inspectorAlert: "Inspector on premises — Alert",
    loyaltyPointsRatio: "Loyalty Points Rate", perSAR: "SAR = 1 point",
    // Day management / invoice system
    invoiceNo: "Invoice #",
    hold: "Hold ⏸", held: "Held",
    roomOccupied: "Room stays occupied", roomFree: "Free the room",
    completePayment: "Complete Payment",
    editInvoice: "Edit Invoice", deleteInvoice: "Delete Invoice",
    endOfDay: "End of Day",
    openingBalance: "Opening Balance", expectedDrawer: "Expected in Drawer",
    itemSales: "Item Sales", qty: "Qty",
    exportCsv: "Export Excel", exportPdf: "Export PDF",
    bulkSelect: "Multi-select", selectAll: "Select All",
    clearSelection: "Clear Selection",
    dateRange: "Range", dateFrom: "From", dateTo: "To",
    printReport: "Print Report",
    heldSessions: "Held Sessions",
    selectToday: "Select Today", selectWeek: "Select Week", selectMonth: "Select Month",
    overview: "Overview", items: "Items",
    endOfDayHour: "End-of-Day Hour",
    endOfDayHourNote: "Hours before this time count as the previous day",
    bulkDelete: "Delete Selected",
    editOrderLines: "Edit Orders",
    removeItem: "Remove Item",
    totalOverride: "Override Total",
    heldOccupied: "Held — Occupied", heldFree: "Held — Free",
    holdTitle: "Hold Session", holdKeepOccupied: "Keep room occupied",
    holdFreeRoom: "Free the room", holdConfirm: "Confirm Hold",
  },
};
