# evolve-skills.ps1
# Memento-style skill evolution: suggests SKILL.md updates based on accumulated lessons
# Usage: .\scripts\evolve-skills.ps1              (check + generate prompt if ready)
#        .\scripts\evolve-skills.ps1 -IndexOnly    (regenerate category index only)
#        .\scripts\evolve-skills.ps1 -Force        (generate prompt regardless of count)
#        .\scripts\evolve-skills.ps1 -MarkEvolved   (reset counter after applying changes)

param(
    [switch]$IndexOnly,
    [switch]$Force,
    [switch]$MarkEvolved,
    [string]$ProjectRoot = "C:\Users\USER\OneDrive\Documents\alsamlah",
    [int]$Threshold = 5
)

$skillName = "ALSAMLAH-assistant"
$lessonsPath = Join-Path $ProjectRoot ".codex\skills\$skillName\tasks\lessons.md"
$skillPath = Join-Path $ProjectRoot ".codex\skills\$skillName\SKILL.md"
$counterPath = Join-Path $ProjectRoot ".codex\skills\$skillName\tasks\.last-evolve-count"
$promptOutputPath = Join-Path $ProjectRoot ".codex\skills\$skillName\tasks\pending-skill-evolution.md"

$content = [System.IO.File]::ReadAllText($lessonsPath, [System.Text.Encoding]::UTF8)
$lessonBlocks = ($content | Select-String -Pattern '## \[\d{4}-\d{2}-\d{2}\]' -AllMatches).Matches.Count

# --- INDEX REGENERATION ---
function Regenerate-Index {
    $blocks = $content -split '(?=## \[\d{4}-\d{2}-\d{2}\])'
    $categories = @{}
    $highLessons = @()

    foreach ($block in $blocks) {
        if ($block -notmatch '## \[(\d{4}-\d{2}-\d{2})\]') { continue }
        $date = $Matches[1]
        $title = ($block -split "`n")[0].Trim()
        $cat = if ($block -match '\*{0,2}Category\*{0,2}:\s*(\[.+?\](?:\[.+?\])*)') { $Matches[1] } else { "UNKNOWN" }
        $weight = if ($block -match '\*{0,2}Weight\*{0,2}:\s*(HIGH|MEDIUM|LOW)') { $Matches[1] } else { "UNKNOWN" }

        # Split multi-category entries like [PATTERN][DOMAIN]
        $catList = $cat -split '\]\[' | ForEach-Object { $_.Trim('[', ']') }
        foreach ($c in $catList) {
            if (-not $categories.ContainsKey($c)) {
                $categories[$c] = @{ Count = 0; Latest = $date; HighCount = 0 }
            }
            $categories[$c].Count++
            if ($date -gt $categories[$c].Latest) { $categories[$c].Latest = $date }
            if ($weight -eq "HIGH") { $categories[$c].HighCount++ }
        }

        if ($weight -eq "HIGH") {
            $highLessons += [PSCustomObject]@{ Date = $date; Title = $title; Categories = $cat }
        }
    }

    # Build index markdown
    $index = "## Category Index`n`n"
    $index += "<!-- AUTO-GENERATED by evolve-skills.ps1 - regenerated $(Get-Date -Format 'yyyy-MM-dd HH:mm') -->`n`n"
    $index += "| Category | Count | Latest | HIGH weight |`n"
    $index += "|----------|-------|--------|-------------|`n"
    foreach ($c in ($categories.Keys | Sort-Object { $categories[$_].Count } -Descending)) {
        $index += "| $c | $($categories[$c].Count) | $($categories[$c].Latest) | $($categories[$c].HighCount) |`n"
    }
    $index += "`n### HIGH weight lessons (read first)`n`n"
    foreach ($h in ($highLessons | Sort-Object Date -Descending)) {
        $cleanTitle = $h.Title -replace '^## ', ''
        $index += "- $cleanTitle`n"
    }
    $index += "`n---`n"

    return $index
}

if ($IndexOnly) {
    $newIndex = Regenerate-Index
    # Replace existing index or insert after header
    if ($content -match '(?s)(## Category Index.+?)(?=## \[\d{4})') {
        $content = $content -replace '(?s)(## Category Index.+?)(?=## \[\d{4})', $newIndex
    } else {
        # Insert after the instructions section (after first ---)
        $firstDash = $content.IndexOf("---")
        if ($firstDash -ge 0) {
            $insertPoint = $content.IndexOf("`n", $firstDash + 3) + 1
            $content = $content.Insert($insertPoint, "`n$newIndex`n")
        }
    }
    [System.IO.File]::WriteAllText($lessonsPath, $content, [System.Text.Encoding]::UTF8)
    Write-Host "Category index regenerated." -ForegroundColor Green
    exit 0
}

if ($MarkEvolved) {
    [System.IO.File]::WriteAllText($counterPath, $lessonBlocks.ToString(), [System.Text.Encoding]::UTF8)
    Write-Host "Evolution counter reset to $lessonBlocks." -ForegroundColor Green
    exit 0
}

# --- CHECK THRESHOLD ---
$lastCount = 0
if (Test-Path $counterPath) {
    $lastCount = [int](Get-Content $counterPath -Raw).Trim()
}
$newLessons = $lessonBlocks - $lastCount

Write-Host ""
Write-Host "Skill Evolution Status" -ForegroundColor Cyan
Write-Host "  Total lessons: $lessonBlocks" -ForegroundColor White
Write-Host "  Since last evolution: $newLessons" -ForegroundColor White
Write-Host "  Threshold: $Threshold" -ForegroundColor DarkGray
Write-Host ""

if ($newLessons -lt $Threshold -and -not $Force) {
    Write-Host "Not enough new lessons yet ($newLessons/$Threshold)." -ForegroundColor Yellow
    Write-Host "Add $($Threshold - $newLessons) more lessons or use -Force." -ForegroundColor DarkGray
    exit 0
}

# --- GENERATE EVOLUTION PROMPT ---
# Collect the newest N lessons
$blocks = $content -split '(?=## \[\d{4}-\d{2}-\d{2}\])'
$recentLessons = @()
foreach ($block in $blocks) {
    if ($block -notmatch '## \[(\d{4}-\d{2}-\d{2}\])') { continue }
    $recentLessons += $block.Trim()
}
$recentLessons = $recentLessons | Select-Object -Last $newLessons

$skillContent = [System.IO.File]::ReadAllText($skillPath, [System.Text.Encoding]::UTF8)

$prompt = @"
## Task: Evolve SKILL.md Based on Recent Lessons (Memento-Style Skill Rewrite)

### Context
$newLessons new lessons have been added since the last SKILL.md evolution.
Review these lessons and propose updates to SKILL.md.

### Current SKILL.md
Read: C:\Users\USER\OneDrive\Documents\alsamlah\.codex\skills\ALSAMLAH-assistant\SKILL.md

### New lessons to incorporate

$($recentLessons -join "`n`n")

### What to do

1. Read the current SKILL.md completely
2. For each new lesson, decide:
   a. Does this lesson introduce a NEW rule that should be in SKILL.md? If yes, add it to the appropriate section.
   b. Does this lesson STRENGTHEN an existing rule? If yes, update the rule with more specificity.
   c. Does this lesson CONTRADICT an existing rule? If yes, update the rule to reflect the correction.
   d. Is this lesson too specific for SKILL.md? If yes, skip it (it stays in lessons.md only).
3. Write the updated SKILL.md
4. After updating SKILL.md, run: .\scripts\evolve-skills.ps1 -MarkEvolved
5. After updating SKILL.md, run: .\scripts\evolve-skills.ps1 -IndexOnly (to regenerate the category index in lessons.md)
6. Run: .\scripts\sync-agent-brain.ps1 (to sync the mirror)

### Rules for SKILL.md updates
- Never remove existing rules unless explicitly superseded
- Keep SKILL.md concise -- rules, not stories
- If a lesson is project-specific (e.g., "EPPlus PivotTable.TableStyle does not exist"), add it as a one-liner under a relevant section, not as a full lesson block
- If a lesson is universal (e.g., "always check nullability before formatting"), it may also belong in universal-lessons.md
- Maintain the existing SKILL.md structure and section ordering
- Update the version date at the top of SKILL.md

### DO NOT
- Do not rewrite the entire SKILL.md from scratch
- Do not remove the Implementation Sequence or Financial Rules sections
- Do not change the file structure (SKILL.md stays a single file)
- Do not modify lessons.md content (only the category index)
"@

[System.IO.File]::WriteAllText($promptOutputPath, $prompt, [System.Text.Encoding]::UTF8)
Write-Host "Evolution prompt generated:" -ForegroundColor Green
Write-Host "  $promptOutputPath" -ForegroundColor White
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Yellow
Write-Host "  1. Open the prompt file and paste it into Claude Code" -ForegroundColor Yellow
Write-Host "  2. Review and approve the SKILL.md changes" -ForegroundColor Yellow
Write-Host "  3. Run: .\scripts\evolve-skills.ps1 -MarkEvolved" -ForegroundColor Yellow
Write-Host "  4. Run: .\scripts\sync-agent-brain.ps1" -ForegroundColor Yellow
Write-Host ""

# Also regenerate the index
$newIndex = Regenerate-Index
if ($content -match '(?s)(## Category Index.+?---)') {
    $content = $content -replace '(?s)(## Category Index.+?---)', $newIndex.TrimEnd()
} else {
    $firstDash = $content.IndexOf("---")
    if ($firstDash -ge 0) {
        $insertPoint = $content.IndexOf("`n", $firstDash + 3) + 1
        $content = $content.Insert($insertPoint, "`n$newIndex`n")
    }
}
[System.IO.File]::WriteAllText($lessonsPath, $content, [System.Text.Encoding]::UTF8)
Write-Host "Category index regenerated in lessons.md." -ForegroundColor Green
